# Démarre d'une base Ubuntu générique
FROM ubuntu:latest

# Met à jour l’index des paquets et met à niveau les paquets installés
RUN apt-get update && apt-get upgrade -y

# Commande par défaut
CMD ["echo", "Hello, World!"]